# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /media/data/r-type/graphical

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /media/data/r-type/graphical

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /media/data/r-type/graphical/CMakeFiles /media/data/r-type/graphical//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /media/data/r-type/graphical/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named graphical_test

# Build rule for target.
graphical_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 graphical_test
.PHONY : graphical_test

# fast build rule for target.
graphical_test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/graphical_test.dir/build.make CMakeFiles/graphical_test.dir/build
.PHONY : graphical_test/fast

#=============================================================================
# Target rules for targets named compile_shaders

# Build rule for target.
compile_shaders: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 compile_shaders
.PHONY : compile_shaders

# fast build rule for target.
compile_shaders/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/compile_shaders.dir/build.make CMakeFiles/compile_shaders.dir/build
.PHONY : compile_shaders/fast

src/render/SpriteRenderer.o: src/render/SpriteRenderer.cpp.o
.PHONY : src/render/SpriteRenderer.o

# target to build an object file
src/render/SpriteRenderer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/graphical_test.dir/build.make CMakeFiles/graphical_test.dir/src/render/SpriteRenderer.cpp.o
.PHONY : src/render/SpriteRenderer.cpp.o

src/render/SpriteRenderer.i: src/render/SpriteRenderer.cpp.i
.PHONY : src/render/SpriteRenderer.i

# target to preprocess a source file
src/render/SpriteRenderer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/graphical_test.dir/build.make CMakeFiles/graphical_test.dir/src/render/SpriteRenderer.cpp.i
.PHONY : src/render/SpriteRenderer.cpp.i

src/render/SpriteRenderer.s: src/render/SpriteRenderer.cpp.s
.PHONY : src/render/SpriteRenderer.s

# target to generate assembly for a file
src/render/SpriteRenderer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/graphical_test.dir/build.make CMakeFiles/graphical_test.dir/src/render/SpriteRenderer.cpp.s
.PHONY : src/render/SpriteRenderer.cpp.s

src/render/VulkanContext.o: src/render/VulkanContext.cpp.o
.PHONY : src/render/VulkanContext.o

# target to build an object file
src/render/VulkanContext.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/graphical_test.dir/build.make CMakeFiles/graphical_test.dir/src/render/VulkanContext.cpp.o
.PHONY : src/render/VulkanContext.cpp.o

src/render/VulkanContext.i: src/render/VulkanContext.cpp.i
.PHONY : src/render/VulkanContext.i

# target to preprocess a source file
src/render/VulkanContext.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/graphical_test.dir/build.make CMakeFiles/graphical_test.dir/src/render/VulkanContext.cpp.i
.PHONY : src/render/VulkanContext.cpp.i

src/render/VulkanContext.s: src/render/VulkanContext.cpp.s
.PHONY : src/render/VulkanContext.s

# target to generate assembly for a file
src/render/VulkanContext.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/graphical_test.dir/build.make CMakeFiles/graphical_test.dir/src/render/VulkanContext.cpp.s
.PHONY : src/render/VulkanContext.cpp.s

src/stb/stb_image.o: src/stb/stb_image.cpp.o
.PHONY : src/stb/stb_image.o

# target to build an object file
src/stb/stb_image.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/graphical_test.dir/build.make CMakeFiles/graphical_test.dir/src/stb/stb_image.cpp.o
.PHONY : src/stb/stb_image.cpp.o

src/stb/stb_image.i: src/stb/stb_image.cpp.i
.PHONY : src/stb/stb_image.i

# target to preprocess a source file
src/stb/stb_image.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/graphical_test.dir/build.make CMakeFiles/graphical_test.dir/src/stb/stb_image.cpp.i
.PHONY : src/stb/stb_image.cpp.i

src/stb/stb_image.s: src/stb/stb_image.cpp.s
.PHONY : src/stb/stb_image.s

# target to generate assembly for a file
src/stb/stb_image.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/graphical_test.dir/build.make CMakeFiles/graphical_test.dir/src/stb/stb_image.cpp.s
.PHONY : src/stb/stb_image.cpp.s

src/texture/textureManager.o: src/texture/textureManager.cpp.o
.PHONY : src/texture/textureManager.o

# target to build an object file
src/texture/textureManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/graphical_test.dir/build.make CMakeFiles/graphical_test.dir/src/texture/textureManager.cpp.o
.PHONY : src/texture/textureManager.cpp.o

src/texture/textureManager.i: src/texture/textureManager.cpp.i
.PHONY : src/texture/textureManager.i

# target to preprocess a source file
src/texture/textureManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/graphical_test.dir/build.make CMakeFiles/graphical_test.dir/src/texture/textureManager.cpp.i
.PHONY : src/texture/textureManager.cpp.i

src/texture/textureManager.s: src/texture/textureManager.cpp.s
.PHONY : src/texture/textureManager.s

# target to generate assembly for a file
src/texture/textureManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/graphical_test.dir/build.make CMakeFiles/graphical_test.dir/src/texture/textureManager.cpp.s
.PHONY : src/texture/textureManager.cpp.s

src/window/windowLinux.o: src/window/windowLinux.cpp.o
.PHONY : src/window/windowLinux.o

# target to build an object file
src/window/windowLinux.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/graphical_test.dir/build.make CMakeFiles/graphical_test.dir/src/window/windowLinux.cpp.o
.PHONY : src/window/windowLinux.cpp.o

src/window/windowLinux.i: src/window/windowLinux.cpp.i
.PHONY : src/window/windowLinux.i

# target to preprocess a source file
src/window/windowLinux.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/graphical_test.dir/build.make CMakeFiles/graphical_test.dir/src/window/windowLinux.cpp.i
.PHONY : src/window/windowLinux.cpp.i

src/window/windowLinux.s: src/window/windowLinux.cpp.s
.PHONY : src/window/windowLinux.s

# target to generate assembly for a file
src/window/windowLinux.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/graphical_test.dir/build.make CMakeFiles/graphical_test.dir/src/window/windowLinux.cpp.s
.PHONY : src/window/windowLinux.cpp.s

test/main.o: test/main.cpp.o
.PHONY : test/main.o

# target to build an object file
test/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/graphical_test.dir/build.make CMakeFiles/graphical_test.dir/test/main.cpp.o
.PHONY : test/main.cpp.o

test/main.i: test/main.cpp.i
.PHONY : test/main.i

# target to preprocess a source file
test/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/graphical_test.dir/build.make CMakeFiles/graphical_test.dir/test/main.cpp.i
.PHONY : test/main.cpp.i

test/main.s: test/main.cpp.s
.PHONY : test/main.s

# target to generate assembly for a file
test/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/graphical_test.dir/build.make CMakeFiles/graphical_test.dir/test/main.cpp.s
.PHONY : test/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... compile_shaders"
	@echo "... graphical_test"
	@echo "... src/render/SpriteRenderer.o"
	@echo "... src/render/SpriteRenderer.i"
	@echo "... src/render/SpriteRenderer.s"
	@echo "... src/render/VulkanContext.o"
	@echo "... src/render/VulkanContext.i"
	@echo "... src/render/VulkanContext.s"
	@echo "... src/stb/stb_image.o"
	@echo "... src/stb/stb_image.i"
	@echo "... src/stb/stb_image.s"
	@echo "... src/texture/textureManager.o"
	@echo "... src/texture/textureManager.i"
	@echo "... src/texture/textureManager.s"
	@echo "... src/window/windowLinux.o"
	@echo "... src/window/windowLinux.i"
	@echo "... src/window/windowLinux.s"
	@echo "... test/main.o"
	@echo "... test/main.i"
	@echo "... test/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

