#pragma once

#include "event/event.hpp"

#include <X11/Xlib.h>
#include <X11/keysym.h>

#define RTK_X11_KEY(name) XKeysymToKeycode(display, XK_##name)

#define KEY_A RTK_X11_KEY(a)
#define KEY_B RTK_X11_KEY(b)
#define KEY_C RTK_X11_KEY(c)
#define KEY_D RTK_X11_KEY(d)
#define KEY_E RTK_X11_KEY(e)
#define KEY_F RTK_X11_KEY(f)
#define KEY_G RTK_X11_KEY(g)
#define KEY_H RTK_X11_KEY(h)
#define KEY_I RTK_X11_KEY(i)
#define KEY_J RTK_X11_KEY(j)
#define KEY_K RTK_X11_KEY(k)
#define KEY_L RTK_X11_KEY(l)
#define KEY_M RTK_X11_KEY(m)
#define KEY_N RTK_X11_KEY(n)
#define KEY_O RTK_X11_KEY(o)
#define KEY_P RTK_X11_KEY(p)
#define KEY_Q RTK_X11_KEY(q)
#define KEY_R RTK_X11_KEY(r)
#define KEY_S RTK_X11_KEY(s)
#define KEY_T RTK_X11_KEY(t)
#define KEY_U RTK_X11_KEY(u)
#define KEY_V RTK_X11_KEY(v)
#define KEY_W RTK_X11_KEY(w)
#define KEY_X RTK_X11_KEY(x)
#define KEY_Y RTK_X11_KEY(y)
#define KEY_Z RTK_X11_KEY(z)

#define KEY_NUM0 RTK_X11_KEY(0)
#define KEY_NUM1 RTK_X11_KEY(1)
#define KEY_NUM2 RTK_X11_KEY(2)
#define KEY_NUM3 RTK_X11_KEY(3)
#define KEY_NUM4 RTK_X11_KEY(4)
#define KEY_NUM5 RTK_X11_KEY(5)
#define KEY_NUM6 RTK_X11_KEY(6)
#define KEY_NUM7 RTK_X11_KEY(7)
#define KEY_NUM8 RTK_X11_KEY(8)
#define KEY_NUM9 RTK_X11_KEY(9)

#define KEY_ESCAPE   RTK_X11_KEY(Escape)
#define KEY_LCONTROL RTK_X11_KEY(Control_L)
#define KEY_LSHIFT   RTK_X11_KEY(Shift_L)
#define KEY_LALT     RTK_X11_KEY(Alt_L)
#define KEY_LSYSTEM  RTK_X11_KEY(Super_L)
#define KEY_RCONTROL RTK_X11_KEY(Control_R)
#define KEY_RSHIFT   RTK_X11_KEY(Shift_R)
#define KEY_RALT     RTK_X11_KEY(Alt_R)
#define KEY_RSYSTEM  RTK_X11_KEY(Super_R)
#define KEY_MENU     RTK_X11_KEY(Menu)

#define KEY_LBRACKET  RTK_X11_KEY(bracketleft)
#define KEY_RBRACKET  RTK_X11_KEY(bracketright)
#define KEY_SEMICOLON RTK_X11_KEY(semicolon)
#define KEY_COMMA     RTK_X11_KEY(comma)
#define KEY_PERIOD    RTK_X11_KEY(period)
#define KEY_QUOTE     RTK_X11_KEY(apostrophe)
#define KEY_SLASH     RTK_X11_KEY(slash)
#define KEY_BACKSLASH RTK_X11_KEY(backslash)
#define KEY_TILDE     RTK_X11_KEY(grave)
#define KEY_EQUAL     RTK_X11_KEY(equal)
#define KEY_HYPHEN    RTK_X11_KEY(minus)

#define KEY_SPACE     RTK_X11_KEY(space)
#define KEY_ENTER     RTK_X11_KEY(Return)
#define KEY_BACKSPACE RTK_X11_KEY(BackSpace)
#define KEY_TAB       RTK_X11_KEY(Tab)

#define KEY_PAGEUP   RTK_X11_KEY(Page_Up)
#define KEY_PAGEDOWN RTK_X11_KEY(Page_Down)
#define KEY_END      RTK_X11_KEY(End)
#define KEY_HOME     RTK_X11_KEY(Home)
#define KEY_INSERT   RTK_X11_KEY(Insert)
#define KEY_DELETE   RTK_X11_KEY(Delete)

#define KEY_ADD      RTK_X11_KEY(KP_Add)
#define KEY_SUBTRACT RTK_X11_KEY(KP_Subtract)
#define KEY_MULTIPLY RTK_X11_KEY(KP_Multiply)
#define KEY_DIVIDE   RTK_X11_KEY(KP_Divide)

#define KEY_LEFT  RTK_X11_KEY(Left)
#define KEY_RIGHT RTK_X11_KEY(Right)
#define KEY_UP    RTK_X11_KEY(Up)
#define KEY_DOWN  RTK_X11_KEY(Down)

#define KEY_NUMPAD0 RTK_X11_KEY(KP_0)
#define KEY_NUMPAD1 RTK_X11_KEY(KP_1)
#define KEY_NUMPAD2 RTK_X11_KEY(KP_2)
#define KEY_NUMPAD3 RTK_X11_KEY(KP_3)
#define KEY_NUMPAD4 RTK_X11_KEY(KP_4)
#define KEY_NUMPAD5 RTK_X11_KEY(KP_5)
#define KEY_NUMPAD6 RTK_X11_KEY(KP_6)
#define KEY_NUMPAD7 RTK_X11_KEY(KP_7)
#define KEY_NUMPAD8 RTK_X11_KEY(KP_8)
#define KEY_NUMPAD9 RTK_X11_KEY(KP_9)

#define KEY_F1  RTK_X11_KEY(F1)
#define KEY_F2  RTK_X11_KEY(F2)
#define KEY_F3  RTK_X11_KEY(F3)
#define KEY_F4  RTK_X11_KEY(F4)
#define KEY_F5  RTK_X11_KEY(F5)
#define KEY_F6  RTK_X11_KEY(F6)
#define KEY_F7  RTK_X11_KEY(F7)
#define KEY_F8  RTK_X11_KEY(F8)
#define KEY_F9  RTK_X11_KEY(F9)
#define KEY_F10 RTK_X11_KEY(F10)
#define KEY_F11 RTK_X11_KEY(F11)
#define KEY_F12 RTK_X11_KEY(F12)
#define KEY_F13 RTK_X11_KEY(F13)
#define KEY_F14 RTK_X11_KEY(F14)
#define KEY_F15 RTK_X11_KEY(F15)
